### PR TITLE
Donovan: Part 1, Part 2

### PR DESCRIPTION
**Pull request by novoio**

### CODE REVIEW

**Comment by vinniefalco** [comment]
This isn't squashed

**Comment by novoio** [comment]
> This isn't squashed

I have tried to break down all the commits for each task.

Would you let me know what you mean by squashing ?

**Comment by vinniefalco** [comment]
> Would you let me know what you mean by squashing ?

Squash means to take multiple commits and merge them into a single commit. You could do this in an interactive rebase for example (`git rebase -i`) or you could do it manually by calling `git reset <commit-id>` followed by `git commit` where `<commit-id>` is the earlier commit you want to squash down to.

> I have tried to break down all the commits for each task.

That's okay too, but if you're going to do that then remove my commit, and the following commit where you revert my commit, from the commit log. You can do this by performing an interactive rebase against an ancestor of my commit. For example `git rebase -i bf57248f`.

Also, why you issuing a pull request against my fork? It should go against the _develop_ branch of the main repo.

**Comment by novoio** [comment]
Do you want me to create a pull request with only one commit?

**Comment by vinniefalco** [comment]
> Do you want me to create a pull request with only one commit?

That's up to you. We can do one commit for each change, or you can squash it all down. But the branch has to be relative to the upstream repo, not my repo, and should not include reverts.

**Pull request closed without merging**
